# Generated by Django 4.2.24 on 2025-11-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("Autos", "Autos"),
                            ("Vida", "Vida"),
                            ("Propiedad", "Propiedad"),
                            ("Comerciales", "Comerciales"),
                            ("Anualidades", "Anualidades"),
                            ("Otro", "Otro"),
                        ],
                        default="Autos",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="leads/"),
                ),
                ("source", models.CharField(default="web_form", max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
